// Generated by CoffeeScript 1.8.0
(function() {
  var __slice = [].slice;

  window.console = window.console || {};

  window.console.log = window.console.log || function() {
    var msg;
    msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    log("LOG " + (msg.join(", ")));
  };

  window.console.info = window.console.info || function() {
    var msg;
    msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    log("[0m[44m[37mINFO: [0m[0m " + (msg.join(", ")));
  };

  window.console.warn = window.console.warn || function() {
    var msg;
    msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    log("[0m[43m[30mWARN: [0m[0m " + (msg.join(", ")));
  };

  window.console.error = window.console.error || function() {
    var msg;
    msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    log("[0m[41m[37m[5mERROR:[0m[0m " + (msg.join(", ")));
  };

  window.console.dir = window.console.dir || function(obj) {
    log(JSON.stringify(obj, null, 4));
  };

  window.console.assert = window.console.assert || function(value, msg) {
    msg = "Assertion Failure: " + (msg || '');
    if (!value) {
      throw new Error(msg);
    }
  };

  window.require = function(path) {
    var module, originalPath;
    console.assert(path, "invalid path:" + path);
    path = String(path);
    module = window["$_fakerequire_" + path];
    if (module != null) {
      return module;
    }
    originalPath = path;
    if (path.substr(-3, 3) !== ".js") {
      path = path.replace(/\./g, '/');
      path = "src/" + path + ".js";
    }
    console.log("[window.require] hand to executeScript:" + path);
    executeScript(path);
    return window["$_fakerequire_" + originalPath];
  };

  window.regRequire || (window.regRequire = function(path, module) {
    console.log("[regRequire] path:" + path);
    console.assert(path, "invalid path:" + path);
    console.assert(module, "invalid module:" + module);
    path = "$_fakerequire_" + path;
    if (window[path]) {
      console.warn("ERROR [regRequire] already exist " + path);
      return;
    }
    window[path] = module;
  });

}).call(this);
